In [1]:
%run -i '../scripts/analysis.py'

In [ ]:
%run -i '../scripts/config.py'

In [2]:
'''
Get all users from Erie for selected time range. 

Only interested in user information, so I use first call, not the updates.
'''
month = 2
days = [11,12,13,14,15,16,17]
sets = [1,2,3,4,5,6]
calls = [1]
num_tweets = 150

collection_type = 'ML'

df = TweetsToDataframe(month,days,sets,calls,num_tweets,collection_type)

df.head()

/Users/jessedecker/projects/tweet_analysis/scripts/cleaning.py:203: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  tweets['hashtags'] = entities[0]
/Users/jessedecker/projects/tweet_analysis/scripts/cleaning.py:204: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  tweets['media'] = entities[1]
/Users/jessedecker/projects/tweet_analysis/scripts/cleaning.py:205: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  tweets['symbols'] = entities[2]
/Users/jessedecker/projects/tweet_analysis/scripts/cleaning.py:206: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  tweets['urls'] = entities[3]
/Users/jessedecker/projects/tweet_analysis/scripts/cleaning.py:207: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  tweets['user_mentions'] = entities[4]

,id_str,text,created_hr,created_dotw,calltime,day,set,call,favorite_count,retweet_count,...,profile_background_color,profile_text_color,user_screen_name,statuses_count,verified,num_tags,num_media,num_symbols,num_urls,num_user_mentions
0,1094936570350747648,First day at my new job ðŸ˜Œ,16,Thu,2019-02-11 07:55:38.984121,11,1,1,0,0,...,F5F8FA,333333,racheeelLehman,126,False,0,0,0,0,0
1,1094936596519026688,@AlexHolleyFOX29 Absolutely!,19,Thu,2019-02-11 07:55:38.984121,11,1,1,0,0,...,F5F8FA,333333,DierolfWilliam,1010,False,0,0,0,0,1
2,1094936629930852352,PM loses moral high ground? I think he lost th...,16,Tue,2019-02-11 07:55:38.984121,11,1,1,0,0,...,F5F8FA,333333,WestPpc,86,False,0,0,0,1,0
3,1094936651741229057,Lawyers of the @TeamCavuto Please Please List...,15,Wed,2019-02-11 07:55:38.984121,11,1,1,0,0,...,000000,000000,DuffGear,1240,False,0,0,0,1,1
4,1094936745190264832,@marklevinshow I AM A PROTECTED CLASS. NO ONE ...,21,Fri,2019-02-11 07:55:38.984121,11,1,1,0,0,...,F5F8FA,333333,SergioAntoni7,5849,False,0,0,0,1,1

In [3]:
erie_users = df[df['place_names'] == 'Erie, PA']
erie_users.head()

,id_str,text,created_hr,created_dotw,calltime,day,set,call,favorite_count,retweet_count,...,profile_background_color,profile_text_color,user_screen_name,statuses_count,verified,num_tags,num_media,num_symbols,num_urls,num_user_mentions
12,1094936894213890048,https://t.co/Zcc1qy2yWZ,1,Mon,2019-02-11 07:55:38.984121,11,1,1,0,0,...,000000,000000,wynterdawn_07,13278,False,0,0,0,1,0
18,1094937051160563712,@SandaBlue Maybe ten or more of my nature Twit...,12,Sat,2019-02-11 07:55:38.984121,11,1,1,0,0,...,C0DEED,333333,JamesIsaak2,216043,False,0,0,0,1,1
22,1094937171763609600,@SandaBlue Lazy fucks,12,Sat,2019-02-11 07:55:38.984121,11,1,1,0,0,...,C0DEED,333333,JamesIsaak2,216044,False,0,0,0,0,1
24,1094937302625910784,@SandaBlue Definitely! Love those greens!,12,Sat,2019-02-11 07:55:38.984121,11,1,1,0,0,...,C0DEED,333333,JamesIsaak2,216045,False,0,0,0,0,1
42,1094938290036330496,@SandaBlue And one of the things we were all t...,12,Sat,2019-02-11 07:55:38.984121,11,1,1,0,0,...,C0DEED,333333,JamesIsaak2,216046,False,0,0,0,1,1

In [5]:
config.WriteCSV(erie_users,'Erie_Users_WK1.csv')